### ISSUE TITLE
Migrate testdata

### ISSUE THREAD

**Issue by itgelo** [qiangxue/go-rest-api#9] opened 2020-05-07 07:30 UTC
`$ make testdata`                                                                                                                                                                            
```
make migrate-reset
make[1]: Entering directory 'HOME_DIR/go/src/go-rest-api'
Resetting database...
Are you sure you want to drop the entire database schema? [y/N]
Aborted dropping the entire database schema
Makefile:112: recipe for target 'migrate-reset' failed
make[1]: *** [migrate-reset] Error 1
make[1]: Leaving directory 'HOME_DIR/go/src/go-rest-api'
Makefile:83: recipe for target 'testdata' failed
make: *** [testdata] Error 2
```
what is the solution?

**Comment by Andrewngabriel** [comment] 2020-05-22 20:03
I am running into the same issue, was anyone able to find a solution?

I would be happy to try and fork it and work on a fix if someone can give me pointers on which file this error is coming from.

**Comment by qiangxue** [comment] 2020-05-23 18:40
Thanks for reporting the issue. It was caused by a BC-breaking change in migrate. I've checked in a fix.

**Closed by qiangxue** 2020-05-23 18:40 UTC
